

import type { DataRecord, AnalysisResult } from '../types';

// Create a type for the dynamic async function. This is safer than eval.
const AsyncFunction = Object.getPrototypeOf(async function(){}).constructor;

// Validation function to check if the result from the executed code has the correct structure.
const isValidResult = (result: any): result is AnalysisResult => {
    if (!result || typeof result !== 'object') return false;
    if (!result.type || !['table', 'chart', 'value', 'statistics', 'error'].includes(result.type)) return false;
    if (typeof result.title !== 'string') return false;
    // summary is optional
    if (typeof result.data === 'undefined') return false;
    return true;
};


export const executeAnalysisCode = async (
    code: string,
    data: DataRecord[]
): Promise<AnalysisResult> => {
    try {
        const analysisFunction = new AsyncFunction('data', code);

        // Execute the function with a timeout to prevent runaway scripts.
        const executionPromise = analysisFunction(data);
        const timeoutPromise = new Promise((_, reject) => 
            setTimeout(() => reject(new Error('Analysis timed out after 5 seconds. The query may be too complex.')), 5000)
        );

        let result = await Promise.race([executionPromise, timeoutPromise]);

        // AI responses can be unpredictable. This block makes parsing more robust.
        if (Array.isArray(result)) {
            // Case 1: The result is a single valid object wrapped in an array, e.g., [{ type: 'table', ... }]
            if (result.length === 1 && isValidResult(result[0])) {
                result = result[0];
            } 
            // Case 2: The result is a raw array of data records, which is a common AI shortcut.
            else {
                 return {
                    type: 'table',
                    title: 'Query Result',
                    summary: 'The AI returned records that have been formatted as a table.',
                    data: result,
                };
            }
        }

        // Validate the structure of the result before returning
        if (!isValidResult(result)) {
            console.error("Execution result is invalid:", JSON.stringify(result, null, 2));
            throw new Error("The code generated by the AI did not return a valid result object. The structure was incorrect.");
        }

        return result;

    } catch (error) {
        console.error("Error executing AI-generated code:", error);
        let errorMessage = "An error occurred while executing the analysis code.";
        if (error instanceof Error) {
            errorMessage = `Execution Error: ${error.message}`;
        }
        // Throw a new error that will be caught by the calling function in App.tsx
        throw new Error(errorMessage);
    }
};

export const executeCleaningCode = async (
    code: string,
    data: DataRecord[]
): Promise<DataRecord[]> => {
    try {
        const cleaningFunction = new AsyncFunction('data', code);

        const executionPromise = cleaningFunction(data);
        const timeoutPromise = new Promise<DataRecord[]>((_, reject) =>
            setTimeout(() => reject(new Error('Data cleaning timed out after 5 seconds.')), 5000)
        );

        const result = await Promise.race([executionPromise, timeoutPromise]);

        if (!Array.isArray(result)) {
            throw new Error('Cleaning code did not return an array as expected.');
        }

        // Optional: Add more validation here to ensure it's an array of objects.
        if (result.length > 0 && typeof result[0] !== 'object') {
             throw new Error('Cleaning code returned an array, but its elements are not objects.');
        }

        return result;

    } catch (error) {
        console.error("Error executing AI-generated cleaning code:", error);
        const errorMessage = error instanceof Error ? `Execution Error: ${error.message}` : "An error occurred while executing the cleaning code.";
        throw new Error(errorMessage);
    }
};